displayName=WorldMapMultiLines
author=Nobody
description=WorldMapMultiLines
tags=kat,worldmap,multizone,multizones,multi,world,map
version=1.0.0
plugins=com.deadmanmultizones.DeadmanMultiZonesPlugin
build=standard