displayName=worldmapmultilines
author=kataraluna
description=worldmapmultilines
tags=kat,worldmap,multizone,multizones,multi,world,map
version=1.0.0
plugins=com.deadmanmultizones.DeadmanMultiZonesPlugin
build=standard
